/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

/**
 *
 * @author David
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    public static final double e = 2.7; //Número Euler
    public static final double π = 3.14; //Número pi

    double operando1 = 0; //Guarda el primer número que metamos
    String operacion = ""; //Guarda la operación pulsada

    public VentanaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        boton07 = new javax.swing.JButton();
        boton08 = new javax.swing.JButton();
        boton09 = new javax.swing.JButton();
        boton04 = new javax.swing.JButton();
        boton05 = new javax.swing.JButton();
        boton06 = new javax.swing.JButton();
        boton01 = new javax.swing.JButton();
        boton02 = new javax.swing.JButton();
        boton03 = new javax.swing.JButton();
        boton00 = new javax.swing.JButton();
        BotonSuma = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        BotonPi = new javax.swing.JButton();
        BotonDivision = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        BotonMultiplicacion = new javax.swing.JButton();
        BotonLogaritmo = new javax.swing.JButton();
        BotonPotenciaCuadrada = new javax.swing.JButton();
        BotonRaizCuadrada = new javax.swing.JButton();
        BotonInvertido = new javax.swing.JButton();
        BotonResto = new javax.swing.JButton();
        BotonPorMenosUno = new javax.swing.JButton();
        BotonPotencia = new javax.swing.JButton();
        BotonDelete = new javax.swing.JButton();
        BotonPunto = new javax.swing.JButton();
        BotonEuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setBackground(new java.awt.Color(0, 0, 0));
        pantalla.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        pantalla.setForeground(new java.awt.Color(0, 255, 51));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");
        pantalla.setOpaque(true);
        getContentPane().add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 450, 58));

        boton07.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton07.setText("7");
        boton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton07ActionPerformed(evt);
            }
        });
        getContentPane().add(boton07, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 64, 64));

        boton08.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton08.setText("8");
        boton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton08ActionPerformed(evt);
            }
        });
        getContentPane().add(boton08, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 64, 64));

        boton09.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton09.setText("9");
        boton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton09ActionPerformed(evt);
            }
        });
        getContentPane().add(boton09, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 64, 64));

        boton04.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton04.setText("4");
        boton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton04ActionPerformed(evt);
            }
        });
        getContentPane().add(boton04, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 64, 64));

        boton05.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton05.setText("5");
        boton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton05ActionPerformed(evt);
            }
        });
        getContentPane().add(boton05, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 64, 64));

        boton06.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton06.setText("6");
        boton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton06ActionPerformed(evt);
            }
        });
        getContentPane().add(boton06, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 64, 64));

        boton01.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton01.setText("1");
        boton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton01ActionPerformed(evt);
            }
        });
        getContentPane().add(boton01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 64, 64));

        boton02.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton02.setText("2");
        boton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton02ActionPerformed(evt);
            }
        });
        getContentPane().add(boton02, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 64, 64));

        boton03.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton03.setText("3");
        boton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton03ActionPerformed(evt);
            }
        });
        getContentPane().add(boton03, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 64, 64));

        boton00.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton00.setText("0");
        boton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton00ActionPerformed(evt);
            }
        });
        getContentPane().add(boton00, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 64, 64));

        BotonSuma.setBackground(new java.awt.Color(153, 153, 153));
        BotonSuma.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BotonSuma.setText("+");
        BotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 64, 64));

        botonIgual.setBackground(new java.awt.Color(153, 153, 153));
        botonIgual.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        getContentPane().add(botonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 130, 64));

        BotonPi.setBackground(new java.awt.Color(204, 204, 204));
        BotonPi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonPi.setText("π");
        BotonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPiActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 64, 30));

        BotonDivision.setBackground(new java.awt.Color(153, 153, 153));
        BotonDivision.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BotonDivision.setText("÷");
        BotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 64, 64));

        BotonResta.setBackground(new java.awt.Color(153, 153, 153));
        BotonResta.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BotonResta.setText("-");
        BotonResta.setOpaque(false);
        BotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 64, 64));

        BotonMultiplicacion.setBackground(new java.awt.Color(153, 153, 153));
        BotonMultiplicacion.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BotonMultiplicacion.setText("X");
        BotonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 64, 64));

        BotonLogaritmo.setBackground(new java.awt.Color(153, 153, 153));
        BotonLogaritmo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonLogaritmo.setText("log");
        BotonLogaritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLogaritmoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonLogaritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 64, 64));

        BotonPotenciaCuadrada.setBackground(new java.awt.Color(153, 153, 153));
        BotonPotenciaCuadrada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonPotenciaCuadrada.setText("x²");
        BotonPotenciaCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPotenciaCuadradaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPotenciaCuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 64, 64));

        BotonRaizCuadrada.setBackground(new java.awt.Color(153, 153, 153));
        BotonRaizCuadrada.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BotonRaizCuadrada.setText("√");
        BotonRaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRaizCuadradaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRaizCuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 64, 64));

        BotonInvertido.setBackground(new java.awt.Color(153, 153, 153));
        BotonInvertido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonInvertido.setText("1/x");
        BotonInvertido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInvertidoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInvertido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 64, 64));

        BotonResto.setBackground(new java.awt.Color(153, 153, 153));
        BotonResto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonResto.setText("mod");
        BotonResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonResto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 64, 64));

        BotonPorMenosUno.setBackground(new java.awt.Color(153, 153, 153));
        BotonPorMenosUno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonPorMenosUno.setText("+/-");
        BotonPorMenosUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPorMenosUnoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPorMenosUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 64, 64));

        BotonPotencia.setBackground(new java.awt.Color(153, 153, 153));
        BotonPotencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonPotencia.setText("x^y");
        BotonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPotenciaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 64, 64));

        BotonDelete.setBackground(new java.awt.Color(204, 255, 255));
        BotonDelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonDelete.setText("C");
        BotonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 64, 64));

        BotonPunto.setBackground(new java.awt.Color(204, 204, 204));
        BotonPunto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonPunto.setText(".");
        BotonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 64, 30));

        BotonEuler.setBackground(new java.awt.Color(204, 204, 204));
        BotonEuler.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonEuler.setText("e");
        BotonEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEulerActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 64, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Números
    private void boton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton07ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("7");
        } else {
            pantalla.setText(auxiliar + "7");
        }
    }//GEN-LAST:event_boton07ActionPerformed

    private void boton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton08ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("8");
        } else {
            pantalla.setText(auxiliar + "8");
        }
    }//GEN-LAST:event_boton08ActionPerformed

    private void boton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton09ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("9");
        } else {
            pantalla.setText(auxiliar + "9");
        }
    }//GEN-LAST:event_boton09ActionPerformed

    private void boton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton04ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("4");
        } else {
            pantalla.setText(auxiliar + "4");
        }
    }//GEN-LAST:event_boton04ActionPerformed

    private void boton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton05ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("5");
        } else {
            pantalla.setText(auxiliar + "5");
        }
    }//GEN-LAST:event_boton05ActionPerformed

    private void boton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton06ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("6");
        } else {
            pantalla.setText(auxiliar + "6");
        }
    }//GEN-LAST:event_boton06ActionPerformed

    private void boton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton01ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("1");
        } else {
            pantalla.setText(auxiliar + "1");
        }
    }//GEN-LAST:event_boton01ActionPerformed

    private void boton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton02ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("2");
        } else {
            pantalla.setText(auxiliar + "2");
        }
    }//GEN-LAST:event_boton02ActionPerformed

    private void boton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton03ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("3");
        } else {
            pantalla.setText(auxiliar + "3");
        }
    }//GEN-LAST:event_boton03ActionPerformed

    private void boton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton00ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("0");
        } else {
            pantalla.setText(auxiliar + "0");
        }
    }//GEN-LAST:event_boton00ActionPerformed
//Operandos
    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        operacion = "+";
        //Double.valueof convierte un string en su equivalente numerico
        operando1 = Double.valueOf(pantalla.getText());
        //Reseteo la pantalla
        pantalla.setText("0");
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        double operando2 = Double.valueOf(pantalla.getText()); //Al pulsar el igual, realiza operaciones.
        if (operacion.equals("+")) {
            operando1 = operando1 + operando2;
        }
        if (operacion.equals("-")) {
            operando1 = operando1 - operando2;
        }
        if (operacion.equals("x")) {
            operando1 = operando1 * operando2;
        }
        if (operacion.equals("÷")) {
            operando1 = operando1 / operando2;
        }
        if (operacion.equals("mod")) {
            operando1 = operando1 % operando2;
        }
        if (operacion.equals("pot")) {
            operando1 = Math.pow(operando1, operando2);
        }
        pantalla.setText("" + operando1);
    }//GEN-LAST:event_botonIgualActionPerformed

    private void BotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivisionActionPerformed
        operacion = "÷";
        //Double.valueof convierte un string en su equivalente numerico
        operando1 = Double.valueOf(pantalla.getText());
        //Reseteo la pantalla
        pantalla.setText("0");
    }//GEN-LAST:event_BotonDivisionActionPerformed

    private void BotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestaActionPerformed
        operacion = "-";
        //Double.valueof convierte un string en su equivalente numerico
        operando1 = Double.valueOf(pantalla.getText());
        //Reseteo la pantalla
        pantalla.setText("0");
    }//GEN-LAST:event_BotonRestaActionPerformed

    private void BotonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPiActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("" + π);
        } else {
            pantalla.setText(auxiliar + π);
        }
    }//GEN-LAST:event_BotonPiActionPerformed

    private void BotonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiplicacionActionPerformed
        operacion = "x";
        //Double.valueof convierte un string en su equivalente numerico
        operando1 = Double.valueOf(pantalla.getText());
        //Reseteo la pantalla
        pantalla.setText("0");
    }//GEN-LAST:event_BotonMultiplicacionActionPerformed

    private void BotonLogaritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLogaritmoActionPerformed
        operando1 = Double.valueOf(pantalla.getText());
        operando1 = Math.log10(operando1); //Logaritmo
        pantalla.setText("" + operando1);

    }//GEN-LAST:event_BotonLogaritmoActionPerformed

    private void BotonPotenciaCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPotenciaCuadradaActionPerformed
        operando1 = Double.valueOf(pantalla.getText());
        operando1 = Math.pow(operando1, (2)); //Potencia
        pantalla.setText("" + operando1);
    }//GEN-LAST:event_BotonPotenciaCuadradaActionPerformed

    private void BotonRaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRaizCuadradaActionPerformed
        operando1 = Double.valueOf(pantalla.getText());
        operando1 = Math.pow(operando1, (0.5)); //Potencia
        pantalla.setText("" + operando1);
    }//GEN-LAST:event_BotonRaizCuadradaActionPerformed

    private void BotonInvertidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInvertidoActionPerformed
        operando1 = Double.valueOf(pantalla.getText());
        operando1 = 1 / operando1;
        pantalla.setText("" + operando1);
    }//GEN-LAST:event_BotonInvertidoActionPerformed

    private void BotonRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestoActionPerformed
        operacion = "mod";
        //Double.valueof convierte un string en su equivalente numerico
        operando1 = Double.valueOf(pantalla.getText());
        //Reseteo la pantalla
        pantalla.setText("0");
    }//GEN-LAST:event_BotonRestoActionPerformed

    private void BotonPorMenosUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPorMenosUnoActionPerformed
        operando1 = Double.valueOf(pantalla.getText());
        operando1 = operando1 * (-1);
        pantalla.setText("" + operando1);
    }//GEN-LAST:event_BotonPorMenosUnoActionPerformed

    private void BotonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPotenciaActionPerformed
        operacion = "pot";
        //Double.valueof convierte un string en su equivalente numerico
        operando1 = Double.valueOf(pantalla.getText());
        //Reseteo la pantalla
        pantalla.setText("0");
    }//GEN-LAST:event_BotonPotenciaActionPerformed

    private void BotonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDeleteActionPerformed
        pantalla.setText("0");
    }//GEN-LAST:event_BotonDeleteActionPerformed

    private void BotonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPuntoActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText(".");
        } else {
            pantalla.setText(auxiliar + ".");
        }
    }//GEN-LAST:event_BotonPuntoActionPerformed

    private void BotonEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEulerActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("" + e);
        } else {
            pantalla.setText(auxiliar + e);
        }
    }//GEN-LAST:event_BotonEulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDelete;
    private javax.swing.JButton BotonDivision;
    private javax.swing.JButton BotonEuler;
    private javax.swing.JButton BotonInvertido;
    private javax.swing.JButton BotonLogaritmo;
    private javax.swing.JButton BotonMultiplicacion;
    private javax.swing.JButton BotonPi;
    private javax.swing.JButton BotonPorMenosUno;
    private javax.swing.JButton BotonPotencia;
    private javax.swing.JButton BotonPotenciaCuadrada;
    private javax.swing.JButton BotonPunto;
    private javax.swing.JButton BotonRaizCuadrada;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonResto;
    private javax.swing.JButton BotonSuma;
    private javax.swing.JButton boton00;
    private javax.swing.JButton boton01;
    private javax.swing.JButton boton02;
    private javax.swing.JButton boton03;
    private javax.swing.JButton boton04;
    private javax.swing.JButton boton05;
    private javax.swing.JButton boton06;
    private javax.swing.JButton boton07;
    private javax.swing.JButton boton08;
    private javax.swing.JButton boton09;
    private javax.swing.JButton botonIgual;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
